name 'isc_kea_test'
maintainer 'Ben Hughes'
maintainer_email 'bmhughes@bmhughes.co.uk'
license 'Apache-2.0'
description 'Installs/Configures isc_kea_test'
version '0.1.0'
chef_version '>= 16.0'
depends 'isc_kea'
