# This is set because the name property doesn't trigger converge_if_changed by default
# And we want to be able to update the subnet when the resource name changes
# Yes, it's a bit horrible ish
Chef/RedundantCode/UnnecessaryDesiredState:
  Exclude:
    - resources/config_dhcp4_subnet.rb
    - resources/config_dhcp4_option_data.rb
    - resources/config_dhcp4_option_def.rb
    - resources/config_dhcp4_shared_network_option_data.rb
    - resources/config_dhcp4_shared_network_subnet_option_data.rb
    - resources/config_dhcp6_subnet.rb
    - resources/config_dhcp4_subnet_pool_option_data.rb
    - resources/config_dhcp6_option_data.rb
    - resources/config_dhcp6_option_def.rb
    - resources/config_dhcp6_shared_network_option_data.rb
    - resources/config_dhcp6_shared_network_subnet_option_data.rb
    - resources/config_dhcp6_subnet_pool_option_data.rb
