name 'isc_kea'
maintainer 'Ben Hughes'
maintainer_email 'bmhughes@bmhughes.co.uk'
license 'Apache-2.0'
description 'Installs/Configures isc_kea'
source_url 'https://github.com/bmhughes/isc_kea'
issues_url 'https://github.com/bmhughes/isc_kea/issues'
chef_version '>= 16.0'
version '0.1.0'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'oracle'
